from __future__ import annotations

from typing import Any, Sequence

def query_devices() -> Any: ...
def play(data: Any, samplerate: int, *, device: int | None = ...) -> None: ...
def wait() -> None: ...
